# 兩個手動 :
# iot/hmd 改成 gaming handhelds
# commercial nb 原本是 chromebook 手動改成 notebook
# 注意 會有 '" '  這樣有空格的資料
# 快速排版 Shift + Alt + F
product_mapping_table = {
    "ar": {
        "commercial nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "au": {
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "bd": {
        "notebook": "notebook",
        "gaming nb": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "be-fr": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "be-nl": {
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "br": {
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "ca-en": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "chromebox": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "graphics",
        "peripherals & accessories": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "ca-fr": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "chromebox": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "graphics",
        "peripherals & accessories": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "ch-de": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "ch-en": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "ch-fr": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "cl": {
        "commercial nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "co": {
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
        "desktop pc": "aio",
        "all-in-one pcs": "aio",
        "vivo pc": "aio",
        "gaming dt": "aio",
    },
    "cz": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "graphic card": "graphics",
        "desktop pc": "lcd",
        "all-in-one pcs": "lcd",
        "vivo pc": "lcd",
        "gaming dt": "lcd",
        "lcd monitors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "de": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "dk": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktoo_lcd",
        "all-in-one pcs": "desktoo_lcd",
        "vivo pc": "desktoo_lcd",
        "gaming dt": "desktoo_lcd",
        "lcd monitors": "desktoo_lcd",
        "chromebox": "desktoo_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "eg": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "desktop pc": "desktop_lcd",
        "all-in-one pcs": "desktop_lcd",
        "vivo pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "chromebox": "desktop_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "projectors": "motherboard",
        "notebook": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "es": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "fi": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktoo_lcd",
        "all-in-one pcs": "desktoo_lcd",
        "vivo pc": "desktoo_lcd",
        "gaming dt": "desktoo_lcd",
        "lcd monitors": "desktoo_lcd",
        "chromebox": "desktoo_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "fr": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "global": {
        "all-in-one pcs": "aio_chrome",
        "chromebox": "aio_chrome",
        "chromebook": "aio_chrome",
        "desktop pc": "desktop",
        "vivo pc": "desktop",
        "nano pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "gaming_nb",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "optical storage": "motherboard",
        "motherboard": "motherboard",
        "desktop chassis": "motherboard",
        "audio cards": "motherboard",
        "computer accessory": "motherboard",
        "peripherals & accessories": "motherboard",
        "rog console pc": "motherboard",
        "rog component": "motherboard",
        "notebook": "notebook",
        "commercial nb": "notebook",
        "asus nuc distribution": "nuc",
        "asus nuc barebone": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
        "nas": "wireless",
    },
    "hk": {
        "commercial nb": "notebook",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "hu": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "id": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "il": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "in": {
        "commercial nb": "notebook",
        "gaming nb": "gaming_nb",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "it": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "all-in-one pcs": "aio",
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "vivo pc": "mini_pc",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "jp": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "kh": {
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "kr": {
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
    },
    "latin": {
        "commercial nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "lk": {
        "commercial nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
    },
    "me-ar": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop_lcd",
        "all-in-one pcs": "desktop_lcd",
        "vivo pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "chromebox": "desktop_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "projectors": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "me-en": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop_lcd",
        "all-in-one pcs": "desktop_lcd",
        "vivo pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "chromebox": "desktop_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "projectors": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "mx": {
        "commercial nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "my": {
        "commercial nb": "notebook",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "nl": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "no": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktoo_lcd",
        "all-in-one pcs": "desktoo_lcd",
        "vivo pc": "desktoo_lcd",
        "gaming dt": "desktoo_lcd",
        "lcd monitors": "desktoo_lcd",
        "chromebox": "desktoo_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "nz": {
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "pe": {
        "commercial nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "ph": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
    },
    "pl": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "dt lcd monitor": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "pt": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "ro": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "all-in-one pcs": "aio_chrome",
        "vivo pc": "aio_chrome",
        "chromebox": "aio_chrome",
        "commercial nb": "notebook",
        "desktop pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "projectors": "desktop_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "sa-en": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop_lcd",
        "all-in-one pcs": "desktop_lcd",
        "vivo pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "chromebox": "desktop_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "projectors": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "se": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktoo_lcd",
        "all-in-one pcs": "desktoo_lcd",
        "vivo pc": "desktoo_lcd",
        "gaming dt": "desktoo_lcd",
        "lcd monitors": "desktoo_lcd",
        "chromebox": "desktoo_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "sg": {
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "sk": {
        "commercial nb": "notebook",
        "graphic card": "graphics",
        "desktop pc": "lcd",
        "all-in-one pcs": "lcd",
        "vivo pc": "lcd",
        "gaming dt": "lcd",
        "lcd monitors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "th": {
        "commercial nb": "notebook",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "tr": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "tw": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "graphic card": "motherboard",
        "desktop chassis": "motherboard",
        "optical storage": "motherboard",
        "audio cards": "motherboard",
        "peripherals & accessories": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
        "intelligent robot": "zenbo",
    },
    "ua-ua": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "all-in-one pcs": "aio",
        "vivo pc": "aio",
        "commercial nb": "notebook",
        "desktop pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "projectors": "desktop_lcd",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "uk": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "all-in-one pcs": "aio_chrome",
        "chromebox": "aio_chrome",
        "commercial nb": "notebook",
        "desktop pc": "desktop_lcd",
        "vivo pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "healthcare system": "wearable",
        "wearable": "wearable",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "us": {
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "chromebox": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "gaming nb": "notebook",
        "graphic card": "graphics",
        "lcd monitors": "graphics",
        "peripherals & accessories": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "vn": {
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "commercial nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "za": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "all-in-one pcs": "aio_chrome",
        "vivo pc": "aio_chrome",
        "chromebox": "aio_chrome",
        "commercial nb": "notebook",
        "desktop pc": "desktop_lcd",
        "gaming dt": "desktop_lcd",
        "lcd monitors": "desktop_lcd",
        "graphic card": "graphics",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
        "zenfone": "phone",
        "premium phone": "phone",
        "padfone": "phone",
        "wireless": "wireless",
        "networking": "wireless",
    },
    "rs-en": {
        "desktop chassis": "accessory",
        "optical storage": "accessory",
        "audio cards": "accessory",
        "peripherals & accessories": "accessory",
        "rog component": "accessory",
        "commercial nb": "notebook",
        "desktop pc": "desktop",
        "all-in-one pcs": "desktop",
        "vivo pc": "desktop",
        "gaming dt": "desktop",
        "chromebox": "desktop",
        "gaming handhelds": "gaming_handhelds",
        "graphic card": "graphics",
        "lcd monitors": "lcd",
        "projectors": "lcd",
        "motherboard": "motherboard",
        "notebook": "notebook",
        "gaming nb": "notebook",
        "asus nuc barebone": "nuc",
        "asus nuc distribution": "nuc",
        "asus nuc elements": "nuc",
        "asus nuc full system": "nuc",
        "zenpad": "pad",
        "eee pad": "pad",
    },
}


def find_productline(site, product_type):
    site_ = site.lower()
    product_type_ = product_type.lower()
    if (
        site_ in product_mapping_table
        and product_type_ in product_mapping_table[site_]
    ):
        return product_mapping_table[site_][product_type_]
    else:
        raise KeyError(
            f"Not supported by Genio, The site = {site} and product_type = {product_type} are not supported by Genio."
        )


# if __name__ == "__main__":
#     site = "tw"
#     product_type = "Notebook"
#     print(find_productline(site, product_type))
